create table if not exists public.coach_history (
    id bigint generated by default as identity primary key,
    user_id text not null,
    career_score integer not null check (career_score between 0 and 100),
    goal text not null,
    current_level text not null,
    score_breakdown jsonb not null default '{}'::jsonb,
    recommendations jsonb not null default '[]'::jsonb,
    daily_insight text not null,
    created_at timestamptz not null default now()
);

create index if not exists coach_history_user_created_idx
    on public.coach_history (user_id, created_at desc);

alter table public.coach_history enable row level security;

-- El backend usa la service role key. No se agrega una política pública para
-- evitar que un usuario pueda consultar el historial de otro usuario.
